# Generated by Django 5.0.3 on 2024-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer',
            old_name='fertilizer_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='poster',
            field=models.CharField(max_length=2000),
        ),
    ]
