# Generated by Django 5.0.3 on 2024-08-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferti', '0002_rename_fertilizer_name_fertilizer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='poster',
            field=models.CharField(max_length=1000),
        ),
    ]
